# Generated by Django 4.2.6 on 2023-10-08 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('code', models.CharField(help_text='Введите код авиакомпании', max_length=20, primary_key=True, serialize=False, verbose_name='код авиакомпании')),
                ('name', models.CharField(help_text='Введите название авиакомпании', max_length=100, verbose_name='название авиакомпании')),
                ('type', models.CharField(help_text='Введите тип авиакомпании', max_length=200, verbose_name='тип')),
                ('fleet_size', models.IntegerField(help_text='Введите рамзер флота', verbose_name='размер флота')),
                ('parent_company', models.CharField(blank=True, help_text='Введите материнскую компанию', max_length=100, null=True, verbose_name='материнская компания')),
            ],
            options={
                'db_table': 'Airline',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('number_flight', models.CharField(help_text='Введите номер рейса', max_length=50, primary_key=True, serialize=False, verbose_name='номер рейса')),
                ('destination', models.CharField(help_text='Введите пункт назначения.', max_length=100, verbose_name='пункт назначения')),
                ('date_of_flight', models.DateField(help_text='Введите дату рейса', verbose_name='дата рейса')),
                ('time_flight', models.TimeField(help_text='Введите время вылета', verbose_name='время вылета')),
                ('check_in', models.CharField(blank=True, help_text='Введите стойки регистрации', max_length=100, null=True, verbose_name='стойки регистрации')),
                ('registration', models.BooleanField(help_text='Регистрация на рейс началась?', verbose_name='регистрация')),
                ('airline', models.ForeignKey(blank=True, help_text='Выберите авиакомпанию, совершающую рейс', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.airline', verbose_name='airline')),
                ('id_user', models.ForeignKey(blank=True, help_text='Введите id рейса', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id рейса')),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passport', models.BigIntegerField(help_text='Введите номер пасспорта', primary_key=True, serialize=False, verbose_name='номер паспорта')),
                ('name', models.CharField(help_text='Введите имя пассажира', max_length=50, verbose_name='имя')),
                ('surname', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Введите отчество', max_length=100, null=True, verbose_name='отчество')),
                ('date_of_birth', models.DateField(help_text='Введите дату рождения', verbose_name='дата рождения')),
                ('with_baggage', models.BooleanField(help_text='Пассажир летит с багажом?', verbose_name='багаж')),
                ('flight', models.ForeignKey(help_text='Выберите рейс пассажира', on_delete=django.db.models.deletion.CASCADE, to='myapp.flights', verbose_name='flight')),
                ('id_user', models.ForeignKey(blank=True, help_text='Введите id пассажира', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пассажира')),
            ],
            options={
                'db_table': 'Passanger',
            },
        ),
        migrations.CreateModel(
            name='Passangers_and_Flights',
            fields=[
                ('id', models.IntegerField(help_text='Введите id', primary_key=True, serialize=False, verbose_name='id')),
                ('id_flight', models.ForeignKey(help_text='Выберите рейс', on_delete=django.db.models.deletion.CASCADE, to='myapp.flights', verbose_name='flight')),
                ('id_passenger', models.ForeignKey(help_text='Выберите пассажира', on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger', verbose_name='passenger')),
            ],
            options={
                'db_table': 'Passangers_and_fligths',
            },
        ),
    ]
