# Generated by Django 4.2.6 on 2023-10-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_passenger_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='with_baggage',
        ),
        migrations.AddField(
            model_name='passangers_and_flights',
            name='with_baggage',
            field=models.BooleanField(blank=True, help_text='Пассажир летит с багажом?', null=True, verbose_name='багаж'),
        ),
    ]
