# Generated by Django 4.2.6 on 2023-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_extra_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='passangers_and_flights',
            name='extra_service',
            field=models.ManyToManyField(blank=True, help_text='Выберите дополнительные услуги', null=True, to='myapp.extra_service', verbose_name='дополнительные услуги'),
        ),
    ]
