# Generated by Django 4.2.6 on 2023-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_passangers_and_flights_extra_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangers_and_flights',
            name='id',
            field=models.AutoField(help_text='Введите id', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
