# Generated by Django 4.2.6 on 2023-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_passangers_and_flights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangers_and_flights',
            name='baggage_weight',
            field=models.IntegerField(blank=True, default=0, help_text='Введите вес багажа', null=True, verbose_name='вес багажа'),
        ),
    ]
