# Generated by Django 4.2.6 on 2023-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_passangers_and_flights_baggage_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangers_and_flights',
            name='with_baggage',
            field=models.BooleanField(blank=True, default=False, help_text='Пассажир летит с багажом?', null=True, verbose_name='багаж'),
        ),
    ]
