# Generated by Django 4.2.6 on 2023-11-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_passangers_and_flights_with_baggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangers_and_flights',
            name='with_baggage',
            field=models.BooleanField(default=False, help_text='Пассажир летит с багажом?', verbose_name='багаж'),
        ),
    ]
